import "../../public/reset.css";
import "@/app/styles/global.css";

import type { Metadata } from "next";
import { color } from "./styles/color";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          backgroundColor: color.white,
          padding: 30,
          overflow: "hidden",
        }}
      >
        {children}
      </body>
    </html>
  );
}
