import "../../public/reset.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { color } from "./styles/color";
import Header from "./components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body style={{ backgroundColor: color.white, padding: 20 }}>
        <Header />
        {children}
      </body>
    </html>
  );
}
